# Generated by Django 4.1.2 on 2022-10-23 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_request_symptoms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="symptoms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, null=True, size=None
            ),
        ),
    ]
