# Generated by Django 4.1.2 on 2022-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="with_google",
            field=models.BooleanField(default=False),
        ),
    ]
