name: Django CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.10.0' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Flake8 action
      uses: py-actions/flake8@v2
      with:
        config: "../setup.cfg"
    - name: Black Check
      uses: jpetrucciani/black-check@22.10.0
      with:
        path: 'api'
        black_flags: '--config pyproject.toml'